In [1]:
import numpy as np
import math

In [2]:
class Chromosome:
    def __init__(self, arr):
        self.__n = len(arr)
        self.__positions = np.array(arr)


    def get_n(self):
        return self.__n


    def get_positions(self):
        return self.__positions


    def print_board(self):
        board = np.zeros((len(self.__positions), len(self.__positions)), 
            dtype = int)
        for i, pos in enumerate(self.__positions):
            board[pos][i] = 15
        print(board)


    # Returns a numpy array.

    def random_vec(self):
        pool = np.arange(self.__n)
        chr = np.zeros(self.__n, dtype = int)
        r = np.random.randint(0, 1 + math.floor((self.__n - 1) / 2 ) )
        chr[0] = r
        pool = np.delete(pool, r)

        for i in range(1, self.__n):
            r = np.random.randint(0, len(pool))
            chr[i] = pool[r]
            pool = np.delete(pool, r)

        return chr


    def make_child(self):
        if self.__n <= 2:
            return self.__positions.copy()
        mutant = self.__positions.copy()
        cols_pool = np.arange(self.__n)
        c1, c2 = np.random.choice(cols_pool, size = 2, replace = False)
        cols_pool = np.delete(cols_pool, np.where( cols_pool == c1))

        if c1 == 0 and self.__positions[c2] > math.floor((self.__n - 1) / 2 ):
            while self.__positions[c2] > math.floor((self.__n - 1) / 2 ):
                cols_pool = np.delete(cols_pool, np.where( cols_pool == c2))
                c2 = np.random.choice(cols_pool)
        elif (c2 == 0 and 
            self.__positions[c1] > math.floor((self.__n - 1) / 2 ) ):

            cols_pool = np.delete(cols_pool, 0)
            c2 = np.random.choice(cols_pool)
        c1, c2 = min(c1,c2), max(c1,c2)
        mutant[c1], mutant[c2] = mutant[c2], mutant[c1]
        return Chromosome(mutant)


    
    # A mutual attack is a pair of queens on the same diagonal.
    # The format grants that there are no queens on the same row or column.
    # Mutual attacks consider an attack between two queens
    # even if there is another queen in the middle.
    # If in a position there are only two queens attacking each other,
    # the number of mutual attacks is 1.
    # The maximum number of mutual attacks is 28, and it occurs when all
    # queens are on the same diagonal.
    

    def mutual_threats(self):
        threats = 0
        for i in range(self.__n):
            for j in range(i + 1, self.__n):
                if abs(i - j) == abs(self.__positions[i]
                                    - self.__positions[j]):

                    threats += 1

        return threats


    # Normalized fitness function
    
    def fitness(self):
        max_threats = self.__n * (self.__n - 1) / 2
        if (self.__n <= 1):
           return 1
        fitness = (max_threats - self.mutual_threats()) / max_threats
        if fitness == 1:
            print(f"SOLUTION FOUND: {self.get_positions()}", end = " ")
        return fitness


In [3]:
print(type(abs(-2)))

<class 'int'>


# Testing

## _ _ init _ _ ( )

In [4]:
base = Chromosome(np.arange(4))
print(base.get_positions())
print(base.get_n())

[0 1 2 3]
4


In [5]:
base.make_child().get_positions()

array([1, 0, 2, 3])

## print_board()

In [6]:
base = Chromosome(np.arange(4))
print(base.get_positions())
print(base.get_n())

[0 1 2 3]
4


In [7]:
base.print_board()

[[15  0  0  0]
 [ 0 15  0  0]
 [ 0  0 15  0]
 [ 0  0  0 15]]


## random_vec()

In [8]:
base = Chromosome(np.arange(5))
random_chr = Chromosome(base.random_vec())
print(random_chr.get_positions())

[1 3 0 4 2]


In [9]:
random_chr.print_board()

[[ 0  0 15  0  0]
 [15  0  0  0  0]
 [ 0  0  0  0 15]
 [ 0 15  0  0  0]
 [ 0  0  0 15  0]]


## make_child()

In [10]:
base = Chromosome(np.arange(5))
chr = Chromosome(base.random_vec())
print(chr.get_positions())

[2 3 4 1 0]


In [11]:
child = chr.make_child()
print(child.get_positions())

[2 3 1 4 0]


## mutual_threats()

In [12]:
base = Chromosome(np.arange(5))
chr = Chromosome(base.random_vec())
print(chr.get_positions())
print(f"chr.mutual_threats(): {chr.mutual_threats()}")


[2 0 4 1 3]
chr.mutual_threats(): 2


In [13]:
chr.print_board()

[[ 0 15  0  0  0]
 [ 0  0  0 15  0]
 [15  0  0  0  0]
 [ 0  0  0  0 15]
 [ 0  0 15  0  0]]


## fitness()

In [14]:
base = Chromosome(np.arange(5))
chr = Chromosome(base.random_vec())
print(chr.get_positions())
print(f"chr.mutual_threats(): {chr.mutual_threats()}")
print(f"chr.fitness(): {chr.fitness()}")

[1 3 4 0 2]
chr.mutual_threats(): 2
chr.fitness(): 0.8


In [15]:
chr.print_board()

[[ 0  0  0 15  0]
 [15  0  0  0  0]
 [ 0  0  0  0 15]
 [ 0 15  0  0  0]
 [ 0  0 15  0  0]]
