In [1]:
import nbimporter
import numpy as np
import random
import time
import math

# import chromosome as Chr

In [2]:
from chromosome import Chromosome

In [3]:
base = Chromosome(np.arange(3))
base.get_positions()

array([0, 1, 2])

In [4]:
class EvolManager:
    def __init__(
        self,
        genes_per_chrom,
        pop,
        generations,
        mating_pool_size = None,
        offspring = None,
        mutation_rate = 0.2,
        ):

        if mating_pool_size is None:
            mating_pool_size = math.floor(pop * 0.5)

        if offspring is None:
            offspring = mating_pool_size * 1.5

        self.__n = genes_per_chrom
        self.__population = pop
        self.__generations = generations
        self.__current_generation = 0
        self.__chrom_array = []
        self.__solutions = []
        self.__sol_generations = np.array([], dtype = int)
        self.__mating_pool = []
        self.__sorted_chrom_array = []
        self.__mating_pool_size = mating_pool_size
        self.__offspring = []
        self.__offspring_size = offspring
        self.__big_arr = []
        self.__solution_times = np.array([])

        self.populate()


    def populate(self):
        proto_chrom = Chromosome(list(range(self.__n)))

        for i in range(self.__population):
            self.__chrom_array.append( 
                Chromosome(proto_chrom.random_chromosome()) )

        for i in range(len(self.__chrom_array)):
            new_sol = True
            if self.__chrom_array[i].fitness() == 1.00:
                for j in range(len(self.__solutions)):
                    if np.array_equal( self.__chrom_array[i].get_positions(),
                        self.__solutions[j].get_positions() ):

                        new_sol = False
                        break
                if new_sol:
                    self.__solutions.append(self.__chrom_array[i])
                    self.__sol_generations = np.append(self.__sol_generations, 
                        self.__current_generation)
                    self.__solution_times = np.append(self.__solution_times, 0)
        print("It's populated over here!")


    def get_chrom_array(self):
        return self.__chrom_array


    def get_solutions(self):
        return self.__solutions


    def get_solution_times(self):
        return self.__solution_times

    
    def get_sol_generations(self):
        return self.__sol_generations


    def get_best_chrom_fitness(self):
        ordered_popul = sorted( self.__chrom_array, 
            key = lambda chrom: - chrom.fitness() )
        return ordered_popul[0].fitness()


    def get_best_chrom_mutual_threats(self):
        ordered_popul = sorted( self.__chrom_array, 
            key = lambda chrom: - chrom.fitness())
        return ordered_popul[0].mutual_threats()


    def get_mating_pool(self):
        return self.__mating_pool


    def get_offspring(self):
        return self.__offspring

    # show_chromosomes
    def show_chrom_positions(self):
        print("__chrom_array members: ")
        for i in self.__chrom_array:
            print(f"{i.get_positions()}", end = " ") 
            print(f"fitness: {i.fitness()}")


# Testing

def __init__(  
> self,  
        genes_per_chrom,  
        pop,  
        generations,  
        mating_pool_size = None,  
        offspring = None,  
        mutation_rate = 0.2,  
        ):

## _ _ init _ _ ( ), populate(), get_chrom_array()

In [6]:
evol_manager = EvolManager(5, 5, 10)
for c in evol_manager.get_chrom_array():
    print(c.get_positions())

It's populated over here!
[2 4 3 0 1]
[2 4 0 3 1]
[0 1 2 3 4]
[2 0 1 3 4]
[2 3 4 1 0]


## get_solutions()

In [7]:
evol_manager = EvolManager(5, 50, 10)
for c in evol_manager.get_chrom_array():
    print(c.get_positions())

SOLUTION FOUND: [2 0 3 1 4]
SOLUTION FOUND: [1 3 0 2 4]
SOLUTION FOUND: [0 3 1 4 2]
It's populated over here!
[0 3 2 4 1]
[1 2 0 3 4]
[0 1 2 3 4]
[0 2 1 4 3]
[1 4 2 3 0]
[0 2 3 1 4]
[0 4 1 2 3]
[2 0 3 4 1]
[2 0 3 4 1]
[2 1 0 3 4]
[2 3 1 0 4]
[1 0 2 4 3]
[2 1 0 4 3]
[1 2 4 0 3]
[1 0 4 2 3]
[0 2 1 3 4]
[2 1 4 0 3]
[1 0 4 2 3]
[1 2 4 3 0]
[0 2 1 4 3]
[1 0 3 4 2]
[0 1 3 4 2]
[2 0 3 1 4]
[0 1 4 2 3]
[1 3 0 2 4]
[2 0 3 4 1]
[2 0 4 3 1]
[0 1 3 4 2]
[0 4 2 1 3]
[0 1 3 2 4]
[0 3 1 4 2]
[0 4 3 1 2]
[1 4 3 0 2]
[0 3 1 2 4]
[1 3 2 4 0]
[1 2 0 4 3]
[0 1 4 2 3]
[1 2 0 3 4]
[1 4 0 3 2]
[2 0 4 1 3]
[2 1 3 4 0]
[0 2 1 3 4]
[0 3 2 1 4]
[1 3 0 4 2]
[0 1 2 3 4]
[2 0 4 1 3]
[1 2 4 0 3]
[1 0 2 4 3]
[2 0 1 3 4]
[1 0 4 2 3]


In [8]:
for c in evol_manager.get_solutions():
    print(c.get_positions())

[2 0 3 1 4]
[1 3 0 2 4]
[0 3 1 4 2]


In [9]:
s0 = Chromosome([2, 0, 3, 1, 4])
s1 = Chromosome([0, 2, 4, 1, 3])
s2 = Chromosome([1, 3, 0, 2, 4])
s3 = Chromosome([1, 4, 2, 0, 3])
s4 = Chromosome([2, 4, 1, 3, 0])
s5 = Chromosome([0, 3, 1, 4, 2])

In [10]:
s0.print_board()

[[ 0 15  0  0  0]
 [ 0  0  0 15  0]
 [15  0  0  0  0]
 [ 0  0 15  0  0]
 [ 0  0  0  0 15]]


In [11]:
s1.print_board()

[[15  0  0  0  0]
 [ 0  0  0 15  0]
 [ 0 15  0  0  0]
 [ 0  0  0  0 15]
 [ 0  0 15  0  0]]


In [12]:
s2.print_board()

[[ 0  0 15  0  0]
 [15  0  0  0  0]
 [ 0  0  0 15  0]
 [ 0 15  0  0  0]
 [ 0  0  0  0 15]]


In [13]:
s3.print_board()

[[ 0  0  0 15  0]
 [15  0  0  0  0]
 [ 0  0 15  0  0]
 [ 0  0  0  0 15]
 [ 0 15  0  0  0]]


In [14]:
s4.print_board()

[[ 0  0  0  0 15]
 [ 0  0 15  0  0]
 [15  0  0  0  0]
 [ 0  0  0 15  0]
 [ 0 15  0  0  0]]


In [15]:
s5.print_board()

[[15  0  0  0  0]
 [ 0  0 15  0  0]
 [ 0  0  0  0 15]
 [ 0 15  0  0  0]
 [ 0  0  0 15  0]]


## get_solution_times()

In [16]:
evol_manager = EvolManager(5, 50, 10)
# for c in evol_manager.get_chrom_array():
#     print(c.get_positions())

SOLUTION FOUND: [2 4 1 3 0]
SOLUTION FOUND: [1 4 2 0 3]
It's populated over here!


In [17]:
evol_manager.get_solution_times()

array([0., 0.])

In [18]:
evol_manager.get_sol_generations()

array([0, 0])

## get_best_chrom_fitness(),  
## get_best_chrom_mutual_threats()

In [19]:
evol_manager = EvolManager(5, 50, 10)
# for c in evol_manager.get_chrom_array():
#     print(c.get_positions())

SOLUTION FOUND: [0 2 4 1 3]
SOLUTION FOUND: [0 3 1 4 2]
SOLUTION FOUND: [2 0 3 1 4]
SOLUTION FOUND: [0 3 1 4 2]
It's populated over here!


In [20]:
evol_manager.get_best_chrom_fitness()

SOLUTION FOUND: [0 2 4 1 3]
SOLUTION FOUND: [0 3 1 4 2]
SOLUTION FOUND: [2 0 3 1 4]
SOLUTION FOUND: [0 3 1 4 2]
SOLUTION FOUND: [0 2 4 1 3]


1.0

In [21]:
evol_manager.get_best_chrom_mutual_threats()

SOLUTION FOUND: [0 2 4 1 3]
SOLUTION FOUND: [0 3 1 4 2]
SOLUTION FOUND: [2 0 3 1 4]
SOLUTION FOUND: [0 3 1 4 2]


0.0

## get_mating_pool()

## get_offspring()

## show_chrom_positions()

In [22]:
evol_manager = EvolManager(5, 5, 10)

SOLUTION FOUND: [1 3 0 2 4]
SOLUTION FOUND: [2 4 1 3 0]
It's populated over here!


In [23]:
evol_manager.show_chrom_positions()

__chrom_array members: 
[1 3 0 2 4] SOLUTION FOUND: [1 3 0 2 4]
fitness: 1.0
[2 3 0 1 4] fitness: 0.6
[0 4 2 1 3] fitness: 0.8
[2 4 1 3 0] SOLUTION FOUND: [2 4 1 3 0]
fitness: 1.0
[0 1 4 2 3] fitness: 0.8
